[workspace]
authors = ["Avitesh Murmu <Aviteshmurmu19@gmail.com>"]
channels = ["conda-forge"]
name = "StevenBlack"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
requests = ">=2.32.5,<3"
flake8 = ">=7.3.0,<8"
